import type { Country } from './interfaces';

export function convertBundleSize(data: number) {
  if (data >= 1000) {
    return `${data / 1000}GB`;
  }

  return `${data}MB`;
}

// place files you want to import through the `$lib` alias in this folder.
export const regions = [
  'Africa',
  'Asia',
  'Europe',
  'Global',
  'Middle East',
  'North America',
  // 'LATAM',
  'Oceania',
  'South America'
];

export const countries: Country[] = [
  { name: 'Iraq', region: 'Middle East', iso: 'IQ' },
  { name: 'Nicaragua', region: 'North America', iso: 'NI' },
  { name: 'Cyprus', region: 'Middle East', iso: 'CY' },
  { name: 'Paraguay', region: 'South America', iso: 'PY' },
  { name: 'Japan', region: 'Asia', iso: 'JP' },
  { name: 'Israel', region: 'Middle East', iso: 'IL' },
  { name: 'India', region: 'Asia', iso: 'IN' },
  { name: 'Austria', region: 'Europe', iso: 'AT' },
  { name: 'Mexico', region: 'North America', iso: 'MX' },
  { name: 'Tunisia', region: 'Africa', iso: 'TN' },
  { name: 'Jordan', region: 'Middle East', iso: 'JO' },
  { name: 'United States', region: 'North America', iso: 'US' },
  { name: 'Guernsey', region: 'Europe', iso: 'GG' },
  { name: 'Lao People`s Democratic Republic', region: 'Asia', iso: 'LA' },
  { name: 'Hawaii', region: 'North America', iso: 'US-HI' },
  { name: 'El Salvador', region: 'North America', iso: 'SV' },
  { name: 'Belgium', region: 'Europe', iso: 'BE' },
  { name: 'Europe+', region: 'Europe', iso: 'Europe+' },
  { name: 'Hong Kong (Special Administrative Region of China)', region: 'Asia', iso: 'HK' },
  { name: 'Brazil', region: 'South America', iso: 'BR' },
  { name: 'Myanmar', region: 'Asia', iso: 'MM' },
  { name: 'Saint Martin (French)', region: 'North America', iso: 'SX' },
  { name: 'Middle East', region: 'Middle East', iso: 'Middle East' },
  { name: 'Holy See (Vatican City State)', region: 'Europe', iso: 'VA' },
  { name: 'Greece', region: 'Europe', iso: 'GR' },
  { name: 'Czech Republic', region: 'Europe', iso: 'CZ' },
  { name: 'Kyrgyzstan', region: 'Asia', iso: 'KG' },
  { name: 'Azerbaijan', region: 'Asia', iso: 'AZ' },
  { name: 'Bolivia', region: 'South America', iso: 'BO' },
  { name: 'North America', region: 'North America', iso: 'North America' },
  { name: 'Hungary', region: 'Europe', iso: 'HU' },
  { name: 'China', region: 'Asia', iso: 'CN' },
  { name: 'Portugal', region: 'Europe', iso: 'PT' },
  { name: 'Guadeloupe', region: 'North America', iso: 'GP' },
  { name: 'Croatia', region: 'Europe', iso: 'HR' },
  { name: 'Estonia', region: 'Europe', iso: 'EE' },
  { name: 'Brunei Darussalam', region: 'Asia', iso: 'BN' },
  { name: 'Gibraltar', region: 'Europe', iso: 'GI' },
  { name: 'Egypt', region: 'Middle East', iso: 'EG' },
  { name: 'Bahrain', region: 'Middle East', iso: 'BH' },
  { name: 'Georgia', region: 'Asia', iso: 'GE' },
  { name: 'Iceland', region: 'Europe', iso: 'IS' },
  { name: 'Central African Republic', region: 'Africa', iso: 'CF' },
  { name: 'Morocco', region: 'Africa', iso: 'MA' },
  { name: 'Thailand', region: 'Asia', iso: 'TH' },
  { name: 'Spain', region: 'Europe', iso: 'ES' },
  { name: 'Tanzania (United Republic of)', region: 'Africa', iso: 'TZ' },
  { name: 'Guatemala', region: 'North America', iso: 'GT' },
  { name: 'Oceania', region: 'Oceania', iso: 'Oceania' },
  { name: 'Monaco', region: 'Europe', iso: 'MC' },
  { name: 'Colombia', region: 'South America', iso: 'CO' },
  { name: 'Qatar', region: 'Middle East', iso: 'QA' },
  { name: 'Montenegro', region: 'Europe', iso: 'ME' },
  { name: 'Africa', region: 'Africa', iso: 'Africa' },
  { name: 'Turkey', region: 'Middle East', iso: 'TR' },
  { name: 'Netherlands', region: 'Europe', iso: 'NL' },
  { name: 'United Arab Emirates', region: 'Middle East', iso: 'AE' },
  { name: 'Senegal', region: 'Africa', iso: 'SN' },
  { name: 'Peru', region: 'South America', iso: 'PE' },
  { name: 'Liechtenstein', region: 'Europe', iso: 'LI' },
  { name: 'Bosnia and Herzegovina', region: 'Europe', iso: 'BA' },
  { name: 'Finland', region: 'Europe', iso: 'FI' },
  { name: 'Cameroon', region: 'Africa', iso: 'CM' },
  { name: 'Dominican Republic', region: 'North America', iso: 'DO' },
  { name: 'Northern Cyprus', region: 'Europe', iso: 'CYP' },
  { name: 'Guam', region: 'Oceania', iso: 'GU' },
  { name: 'Kazakhstan', region: 'Asia', iso: 'KZ' },
  { name: 'Costa Rica', region: 'North America', iso: 'CR' },
  { name: 'Indonesia', region: 'Asia', iso: 'ID' },
  { name: 'Ecuador', region: 'South America', iso: 'EC' },
  { name: 'Kuwait', region: 'Middle East', iso: 'KW' },
  { name: 'Taiwan', region: 'Asia', iso: 'TW' },
  { name: 'Tajikistan', region: 'Asia', iso: 'TJ' },
  { name: 'Kosovo', region: 'Europe', iso: 'XK' },
  { name: 'Ireland', region: 'Europe', iso: 'IE' },
  { name: 'Chile', region: 'South America', iso: 'CL' },
  { name: 'Vietnam', region: 'Asia', iso: 'VN' },
  { name: 'Bulgaria', region: 'Europe', iso: 'BG' },
  { name: 'Asia', region: 'Asia', iso: 'Asia' },
  { name: 'Jersey', region: 'Europe', iso: 'JE' },
  { name: 'Saudi Arabia', region: 'Middle East', iso: 'SA' },
  { name: 'Republic of Korea', region: 'Asia', iso: 'KR' },
  { name: 'Democratic Republic of the Congo', region: 'Africa', iso: 'CD' },
  { name: 'North Macedonia (Republic of North Macedonia)', region: 'Europe', iso: 'MK' },
  { name: 'Norway', region: 'Europe', iso: 'NO' },
  { name: 'Sweden', region: 'Europe', iso: 'SE' },
  { name: 'Isle Of Man', region: 'Europe', iso: 'IM' },
  { name: 'France', region: 'Europe', iso: 'FR' },
  { name: 'Uruguay', region: 'South America', iso: 'UY' },
  { name: 'Botswana', region: 'Africa', iso: 'BW' },
  { name: 'Switzerland', region: 'Europe', iso: 'CH' },
  { name: 'Mongolia', region: 'Asia', iso: 'MN' },
  { name: 'Argentina', region: 'South America', iso: 'AR' },
  { name: 'Nigeria', region: 'Africa', iso: 'NG' },
  { name: 'Poland', region: 'Europe', iso: 'PL' },
  { name: 'Guinea-Bissau', region: 'Africa', iso: 'GW' },
  { name: 'Reunion', region: 'Africa', iso: 'RE' },
  { name: 'Singapore', region: 'Asia', iso: 'SG' },
  { name: 'Malaysia', region: 'Asia', iso: 'MY' },
  { name: 'Ghana', region: 'Africa', iso: 'GH' },
  { name: 'Romania', region: 'Europe', iso: 'RO' },
  { name: 'Sri Lanka', region: 'Asia', iso: 'LK' },
  { name: 'Global', region: 'Global', iso: 'Global' },
  { name: 'Madagascar', region: 'Africa', iso: 'MG' },
  { name: 'Andorra', region: 'Europe', iso: 'AD' },
  { name: 'LATAM', region: 'South America', iso: 'LATAM' },
  { name: 'Cote d`Ivoire', region: 'Africa', iso: 'CI' },
  { name: 'Cambodia', region: 'Asia', iso: 'KH' },
  { name: 'Pakistan', region: 'Asia', iso: 'PK' },
  { name: 'Gabon', region: 'Africa', iso: 'GA' },
  { name: 'Kenya', region: 'Africa', iso: 'KE' },
  { name: 'Slovenia', region: 'Europe', iso: 'SI' },
  { name: 'Albania', region: 'Europe', iso: 'AL' },
  { name: 'Philippines', region: 'Asia', iso: 'PH' },
  { name: 'Congo', region: 'Africa', iso: 'CG' },
  { name: 'Oman', region: 'Middle East', iso: 'OM' },
  { name: 'New Zealand', region: 'Oceania', iso: 'NZ' },
  { name: 'Russian Federation', region: 'Europe', iso: 'RU' },
  { name: 'Panama', region: 'South America', iso: 'PA' },
  { name: 'Malawi', region: 'Africa', iso: 'MW' },
  { name: 'Luxembourg', region: 'Europe', iso: 'LU' },
  { name: 'Serbia', region: 'Europe', iso: 'RS' },
  { name: 'Aland Islands', region: 'Europe', iso: 'AX' },
  { name: 'Ukraine', region: 'Europe', iso: 'UA' },
  { name: 'Armenia', region: 'Asia', iso: 'AM' },
  { name: 'Seychelles', region: 'Africa', iso: 'SC' },
  { name: 'Niger', region: 'Africa', iso: 'NE' },
  { name: 'Yemen', region: 'Middle East', iso: 'YE' },
  { name: 'Macau (Special Administrative Region of China)', region: 'Asia', iso: 'MO' },
  { name: 'Latvia', region: 'Europe', iso: 'LV' },
  { name: 'Denmark', region: 'Europe', iso: 'DK' },
  { name: 'Canada', region: 'North America', iso: 'CA' },
  { name: 'Zambia', region: 'Africa', iso: 'ZM' },
  { name: 'Australia', region: 'Oceania', iso: 'AU' },
  { name: 'French Southern Territories', region: 'Africa', iso: 'TF' },
  { name: 'Moldova (Republic of)', region: 'Europe', iso: 'MD' },
  { name: 'French Guiana', region: 'South America', iso: 'GF' },
  { name: 'Mali', region: 'Africa', iso: 'ML' },
  { name: 'Martinique', region: 'North America', iso: 'MQ' },
  { name: 'Slovakia', region: 'Europe', iso: 'SK' },
  { name: 'United Kingdom', region: 'Europe', iso: 'GB' },
  { name: 'Italy', region: 'Europe', iso: 'IT' },
  { name: 'South Africa', region: 'Africa', iso: 'ZA' },
  { name: 'Chad', region: 'Africa', iso: 'TD' },
  { name: 'Swaziland', region: 'Africa', iso: 'SZ' },
  { name: 'Saint Barthelemy', region: 'North America', iso: 'BL' },
  { name: 'Germany', region: 'Europe', iso: 'DE' },
  { name: 'Canary Islands', region: 'Europe', iso: 'IC' },
  { name: 'Malta', region: 'Europe', iso: 'MT' },
  { name: 'Bangladesh', region: 'Asia', iso: 'BD' },
  { name: 'Uganda', region: 'Africa', iso: 'UG' },
  { name: 'Liberia', region: 'Africa', iso: 'LR' },
  { name: 'Uzbekistan', region: 'Asia', iso: 'UZ' },
  { name: 'Algeria', region: 'Africa', iso: 'DZ' },
  { name: 'Lithuania', region: 'Europe', iso: 'LT' },
  { name: 'Afghanistan', region: 'Asia', iso: 'AF' },
  { name: 'American Samoa', region: 'Oceania', iso: 'AS' },
  { name: 'Angola', region: 'Africa', iso: 'AO' },
  { name: 'Anguilla', region: 'North America', iso: 'AI' },
  { name: 'Antarctica', region: 'Global', iso: 'AQ' },
  { name: 'Antigua and Barbuda', region: 'North America', iso: 'AG' },
  { name: 'Aruba', region: 'North America', iso: 'AW' },
  { name: 'Bahamas (the)', region: 'North America', iso: 'BS' },
  { name: 'Barbados', region: 'North America', iso: 'BB' },
  { name: 'Belarus', region: 'Europe', iso: 'BY' },
  { name: 'Belize', region: 'North America', iso: 'BZ' },
  { name: 'Benin', region: 'Africa', iso: 'BJ' },
  { name: 'Bermuda', region: 'North America', iso: 'BM' },
  { name: 'Bhutan', region: 'Asia', iso: 'BT' },
  { name: 'Bonaire, Sint Eustatius and Saba', region: 'North America', iso: 'BQ' },
  { name: 'Bouvet Island', region: 'Global', iso: 'BV' },
  { name: 'British Indian Ocean Territory (the)', region: 'Global', iso: 'IO' },
  { name: 'Burkina Faso', region: 'Africa', iso: 'BF' },
  { name: 'Burundi', region: 'Africa', iso: 'BI' },
  { name: 'Cabo Verde', region: 'Africa', iso: 'CV' },
  { name: 'Cayman Islands (the)', region: 'North America', iso: 'KY' },
  { name: 'Christmas Island', region: 'Oceania', iso: 'CX' },
  { name: 'Cocos (Keeling) Islands (the)', region: 'Oceania', iso: 'CC' },
  { name: 'Comoros (the)', region: 'Africa', iso: 'KM' },
  { name: 'Cook Islands (the)', region: 'Oceania', iso: 'CK' },
  { name: 'Cuba', region: 'North America', iso: 'CU' },
  { name: 'Curaçao', region: 'North America', iso: 'CW' },
  { name: 'Djibouti', region: 'Africa', iso: 'DJ' },
  { name: 'Dominica', region: 'North America', iso: 'DM' },
  { name: 'Equatorial Guinea', region: 'Africa', iso: 'GQ' },
  { name: 'Eritrea', region: 'Africa', iso: 'ER' },
  { name: 'Ethiopia', region: 'Africa', iso: 'ET' },
  { name: 'Falkland Islands (the) [Malvinas]', region: 'South America', iso: 'FK' },
  { name: 'Faroe Islands (the)', region: 'Europe', iso: 'FO' },
  { name: 'Fiji', region: 'Oceania', iso: 'FJ' },
  { name: 'French Polynesia', region: 'Oceania', iso: 'PF' },
  { name: 'Gambia (the)', region: 'Africa', iso: 'GM' },
  { name: 'Greenland', region: 'North America', iso: 'GL' },
  { name: 'Grenada', region: 'North America', iso: 'GD' },
  { name: 'Guinea', region: 'Africa', iso: 'GN' },
  { name: 'Guyana', region: 'South America', iso: 'GY' },
  { name: 'Haiti', region: 'North America', iso: 'HT' },
  { name: 'Heard Island and McDonald Islands', region: 'Global', iso: 'HM' },
  { name: 'Honduras', region: 'North America', iso: 'HN' },
  { name: 'Iran (Islamic Republic of)', region: 'Middle East', iso: 'IR' },
  { name: 'Jamaica', region: 'North America', iso: 'JM' },
  { name: 'Kiribati', region: 'Oceania', iso: 'KI' },
  { name: "Korea (the Democratic People's Republic of)", region: 'Asia', iso: 'KP' },
  { name: 'Lebanon', region: 'Middle East', iso: 'LB' },
  { name: 'Lesotho', region: 'Africa', iso: 'LS' },
  { name: 'Libya', region: 'Africa', iso: 'LY' },
  { name: 'Maldives', region: 'Asia', iso: 'MV' },
  { name: 'Marshall Islands (the)', region: 'Oceania', iso: 'MH' },
  { name: 'Mauritania', region: 'Africa', iso: 'MR' },
  { name: 'Mauritius', region: 'Africa', iso: 'MU' },
  { name: 'Mayotte', region: 'Africa', iso: 'YT' },
  { name: 'Micronesia (Federated States of)', region: 'Oceania', iso: 'FM' },
  { name: 'Montserrat', region: 'North America', iso: 'MS' },
  { name: 'Mozambique', region: 'Africa', iso: 'MZ' },
  { name: 'Namibia', region: 'Africa', iso: 'NA' },
  { name: 'Nauru', region: 'Oceania', iso: 'NR' },
  { name: 'Nepal', region: 'Asia', iso: 'NP' },
  { name: 'New Caledonia', region: 'Oceania', iso: 'NC' },
  { name: 'Niue', region: 'Oceania', iso: 'NU' },
  { name: 'Norfolk Island', region: 'Oceania', iso: 'NF' },
  { name: 'Northern Mariana Islands (the)', region: 'Oceania', iso: 'MP' },
  { name: 'Palau', region: 'Oceania', iso: 'PW' },
  { name: 'Palestine, State of', region: 'Middle East', iso: 'PS' },
  { name: 'Papua New Guinea', region: 'Oceania', iso: 'PG' },
  { name: 'Pitcairn', region: 'Oceania', iso: 'PN' },
  { name: 'Puerto Rico', region: 'North America', iso: 'PR' },
  { name: 'Rwanda', region: 'Africa', iso: 'RW' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', region: 'Africa', iso: 'SH' },
  { name: 'Saint Kitts and Nevis', region: 'North America', iso: 'KN' },
  { name: 'Saint Lucia', region: 'North America', iso: 'LC' },
  { name: 'Saint Martin (French part)', region: 'North America', iso: 'MF' },
  { name: 'Saint Pierre and Miquelon', region: 'North America', iso: 'PM' },
  { name: 'Saint Vincent and the Grenadines', region: 'North America', iso: 'VC' },
  { name: 'Samoa', region: 'Oceania', iso: 'WS' },
  { name: 'San Marino', region: 'Europe', iso: 'SM' },
  { name: 'Sao Tome and Principe', region: 'Africa', iso: 'ST' },
  { name: 'Sierra Leone', region: 'Africa', iso: 'SL' },
  { name: 'Solomon Islands', region: 'Oceania', iso: 'SB' },
  { name: 'Somalia', region: 'Africa', iso: 'SO' },
  { name: 'South Georgia and the South Sandwich Islands', region: 'Global', iso: 'GS' },
  { name: 'South Sudan', region: 'Africa', iso: 'SS' },
  { name: 'Sudan (the)', region: 'Africa', iso: 'SD' },
  { name: 'Suriname', region: 'South America', iso: 'SR' },
  { name: 'Svalbard and Jan Mayen', region: 'Europe', iso: 'SJ' },
  { name: 'Syrian Arab Republic', region: 'Middle East', iso: 'SY' },
  { name: 'Taiwan (Province of China)', region: 'Asia', iso: 'TW' },
  { name: 'Timor-Leste', region: 'Asia', iso: 'TL' },
  { name: 'Tokelau', region: 'Oceania', iso: 'TK' },
  { name: 'Tonga', region: 'Oceania', iso: 'TO' },
  { name: 'Trinidad and Tobago', region: 'North America', iso: 'TT' },
  { name: 'Turks and Caicos Islands (the)', region: 'North America', iso: 'TC' },
  { name: 'Tuvalu', region: 'Oceania', iso: 'TV' },
  { name: 'United States Minor Outlying Islands (the)', region: 'North America', iso: 'UM' },
  { name: 'Virgin Islands (British)', region: 'North America', iso: 'VG' },
  { name: 'Virgin Islands (U.S.)', region: 'North America', iso: 'VI' },
  { name: 'Wallis and Futuna', region: 'Oceania', iso: 'WF' },
  { name: 'Western Sahara', region: 'Africa', iso: 'EH' },
  { name: 'Zimbabwe', region: 'Africa', iso: 'ZW' },
  { name: 'Togo', region: 'Africa', iso: 'TG' },
  { name: 'Turkmenistan', region: 'Asia', iso: 'TM' },
  { name: 'Vanuatu', region: 'Oceania', iso: 'VU' },
  { name: 'Venezuela (Bolivarian Republic of)', region: 'South America', iso: 'VE' }
];
